### ISSUE TITLE
data of website

### ISSUE THREAD

**Issue by geoHeil** [decarbnow/data#2]
Can you give a little bit of documentation about the datasets? 
Are all the data points here reflecting 1:1 what is available on the layers from the web map? Will these be updated in cadence with the data on the website?

I envision potentially using some of the data points here for a research project. Are there certain licensing terms to consider?

**Comment by stefjow** [comment]
Data documentation will be constantly added, but we have been a bit careless.

The points and layers on the map are hosted in this repository and reflect 1:1 what you can experience on the map.

All the data we use is freely available. We have linked the data sources in the readme.md files in the respective folders. You will find the licensing terms there.

If you have any further questions, we are happy to help!

**Comment by geoHeil** [comment]
Great thanks!

**Comment by geoHeil** [comment]
@sweing do you share somewhere the scripts which were used to download or process the raw data files? For example, https://github.com/decarbnow/data/tree/master/layers/eu-ets is linking to https://climate.ec.europa.eu/eu-action/eu-emissions-trading-system-eu-ets_en but I cannot find the downloads anywhere on their site.

**Comment by stefjow** [comment]
@geoHeil the data is a bit hidden in "Union registry": https://climate.ec.europa.eu/eu-action/eu-emissions-trading-system-eu-ets/union-registry_en

Reports -> 01/04/2022 - Verified Emissions for 2021

For geolocating the companies we used the data from https://euets.info/. You can also just use the data from there. But be careful: Not all companies are correctly geolocated - some (sub-)companies have the same coordinates. We corrected the location of the voestalpine Kalkwerk Steyrling.
